from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from app.database import Base

# ==========================================
# QUIZ QUESTION DATABASE MODEL
# ==========================================
# This class defines the 'quiz_questions' table in our database.
# QuizQuestions are multiple-choice questions generated by AI.
class QuizQuestion(Base):
    __tablename__ = "quiz_questions"

    id = Column(Integer, primary_key=True, index=True)
    question = Column(String, nullable=False)
    
    # Store options as a string, e.g., JSON-serialized list or semicolon-separated options
    options = Column(String, nullable=False)
    correct_answer = Column(String, nullable=False)
    
    # Foreign key linking this question to a study item
    item_id = Column(Integer, ForeignKey("items.id"), nullable=False)

    # Relationship linking this question back to its Item
    item = relationship("Item", back_populates="quiz_questions")
