from pydantic import BaseModel, Field
from typing import Optional

# ==========================================
# CONCEPT: BASE SCHEMA
# ==========================================
# ItemBase contains fields that are common to both reading and writing study items.
# Sharing these fields prevents duplicating code.
class ItemBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=100, description="The title of the study item (e.g., 'Learn Python Basics')")
    description: Optional[str] = Field(None, max_length=500, description="A detailed description of the study topic")

# ==========================================
# CONCEPT: CREATION SCHEMA
# ==========================================
# ItemCreate is used when creating a new item. It inherits from ItemBase.
# The user doesn't specify an ID or completed status during creation, so they aren't here.
class ItemCreate(ItemBase):
    pass

# ==========================================
# CONCEPT: UPDATE SCHEMA
# ==========================================
# ItemUpdate is used when modifying an existing item.
# Here, the user can toggle the 'completed' state or edit the fields.
# We make fields optional so they only update what they provide.
class ItemUpdate(BaseModel):
    title: Optional[str] = Field(None, min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=500)
    completed: Optional[bool] = Field(None, description="Mark the study topic as done or in-progress")

# ==========================================
# CONCEPT: RESPONSE SCHEMA (SERIALIZATION)
# ==========================================
# ItemResponse is used to format the data sent back to the user.
# It includes the 'id' (which is generated by the server/database) and 'completed'.
# In Pydantic v2, we use 'model_config = {"from_attributes": True}' to allow Pydantic 
# to read SQLAlchemy models as dictionaries.
class ItemResponse(ItemBase):
    id: int
    completed: bool

    model_config = {
        "from_attributes": True
    }
